//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService1
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Book()
        {
            this.ID_user = 1;
            this.T_Journal = new HashSet<T_Journal>();
        }
    
        public int ID_book { get; set; }
        public int ID_author { get; set; }
        public int ID_genre { get; set; }
        public Nullable<bool> Available { get; set; }
        public string Book_name { get; set; }
        public int ID_user { get; set; }
    
        public virtual T_Author T_Author { get; set; }
        public virtual T_Genre T_Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Journal> T_Journal { get; set; }
    }
}
